version: "3.0"

services:
  pihole:
    container_name: pihole
    build:
      dockerfile: ./pihole-unbound/Dockerfile
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT:-80}:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      - FTLCONF_dns_interface=192.168.50.10
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${WEBPASSWORD}
      - WEBTHEME=${WEBTHEME:-default-light}
      - FTLCONF_dns_revServers=true,192.168.50.0/24,192.168.50.1:53,local
      - FTLCONF_dns_interface=127.0.0.1
      - FTLCONF_dns_upstreams=127.0.0.1#5335
      - FTLCONF_dns_listeningMode=single

    restart: unless-stopped
